const { getFirestore, FieldValue } = require('firebase-admin/firestore');
const { generateTasksFromTemplates } = require('../utils/templateManager');

exports.getTemplates = async (req, res) => {
  try {
    const db = getFirestore();
    const orgId = req.session.user.organization_id;

    // Fetch active global templates
    const templatesSnap = await db.collection('global_templates')
      .where('organization_id', '==', orgId)
      .get();

    const templates = templatesSnap.docs.map(doc => ({ id: doc.id, ...doc.data() }));

    // Fetch related master data in parallel
    const [clientsSnap, typesSnap, usersSnap] = await Promise.all([
      db.collection('clients').where('organization_id', '==', orgId).get(),
      db.collection('task_types').where('organization_id', '==', orgId).get(),
      db.collection('users').where('organization_id', '==', orgId).get()
    ]);

    const typeMap = {}; typesSnap.forEach(d => typeMap[d.id] = { id: d.id, ...d.data() });
    const userMap = {}; usersSnap.forEach(d => userMap[d.id] = { id: d.id, ...d.data() });

    const mappedTemplates = templates.map(t => ({
      ...t,
      TaskType: t.task_type_id ? typeMap[t.task_type_id] : null,
      Assignee: t.assigned_user_id ? userMap[t.assigned_user_id] : null
    }));

    const clients = clientsSnap.docs.map(doc => ({ id: doc.id, ...doc.data() }));
    const taskTypes = typesSnap.docs.map(doc => ({ id: doc.id, ...doc.data() }));
    const users = usersSnap.docs.map(doc => ({ id: doc.id, ...doc.data() }));

    res.render('pages/templates', { templates: mappedTemplates, clients, taskTypes, users });
  } catch (err) {
    console.error(err);
    res.status(500).send('Internal Server Error');
  }
};

exports.apiCreateTemplate = async (req, res) => {
  try {
    const db = getFirestore();
    const orgId = req.session.user.organization_id;
    const { task_type_id, assigned_user_id, recurrence_rule, tags } = req.body;

    if (!task_type_id || !recurrence_rule) {
      return res.status(400).json({ error: 'Task Type and Recurrence Rule are required' });
    }

    let parsedTags = [];
    if (tags) {
      if (typeof tags === 'string') {
        parsedTags = tags.split(',').map(t => t.trim()).filter(t => t);
      } else if (Array.isArray(tags)) {
        parsedTags = tags;
      }
    }

    const docRef = await db.collection('global_templates').add({
      organization_id: orgId,
      task_type_id,
      assigned_user_id: assigned_user_id || null,
      recurrence_rule,
      tags: parsedTags,
      created_by: req.session.user.id,
      created_at: FieldValue.serverTimestamp()
    });

    // Instantly generate tasks for existing clients
    await generateTasksFromTemplates(db, orgId, true);

    res.json({ success: true, id: docRef.id });
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server Error' });
  }
};

exports.deleteTemplate = async (req, res) => {
  try {
    const db = getFirestore();
    const orgId = req.session.user.organization_id;
    const templateId = req.params.id;

    const docRef = db.collection('global_templates').doc(templateId);
    const doc = await docRef.get();

    if (doc.exists && doc.data().organization_id === orgId) {
      await docRef.delete();

      // Soft-delete incomplete tasks generated by this template
      const tasksSnap = await db.collection('tasks')
        .where('organization_id', '==', orgId)
        .where('global_template_id', '==', templateId)
        .where('status', '!=', 'Completed')
        .get();

      const batch = db.batch();
      tasksSnap.forEach(doc => {
        batch.update(doc.ref, { deleted_at: FieldValue.serverTimestamp() });
      });
      await batch.commit();

      res.json({ success: true });
    } else {
      res.status(404).json({ error: 'Template not found' });
    }
  } catch (err) {
    console.error(err);
    res.status(500).json({ error: 'Server Error' });
  }
};
